In [75]:
import pandas as pd
data = pd.read_csv('df-clean.csv', sep='\t')
import math
import numpy as np
import time

In [ ]:
client = MongoClient('localhost', 27017)
db = client['hw4']
appdata = db['appdata']

In [76]:
def eucDist(x, y):
    if len(x) != len(y):
        print("The given points aren't in the same dimension")
    else:
        sq_dist = 0
        for i in range(len(x)):
            sq_dist += (x[i] + y[i])**2
        sq_dist = math.sqrt(sq_dist)
        return sq_dist
        

In [202]:
old_centroids = []
def get_centroids(matrix, k):
    #get k random numbers in the range of the length of the array
    cents = np.random.randint(len(matrix), size=k)
    #use the k random numbers to take the rows matching the random values of for k
    centroids = matrix[cents,:]
    if len(centroids) !=k:
        while old_centroids.all(centroids) == True:
            cents = np.random.randint(len(matrix), size=k)
            centroids = matrix[cents,:]
        old_centroids.append(centroids)
    else:
        old_centroids.append(centroids)
    print(centroids)
    return centroids


In [78]:
data = data[['1', '2', '3', '4', '5']]

In [79]:
matrix1 = data.values

In [173]:
def getMinDistanceCentroids(matrix, centroids):
    dist = 0
    for point in matrix:
        dists = []
        for centroid in centroids:
            dists.append(eucDist(point, centroid))
        dists_a = np.asarray(dists)
        dist += min(dists_a,key=float)
        '''        print(dists)
        print(min(dists,key=float))
        print(dist)'''
    return dist
            


distances:
    check what centroid is the closest to the given points
    get next set of centroids
    check if sums of distances to the centroids is smaller than the previous one. If yes, set  new centroids and get new pairs

In [200]:
def getClusters(matrix, k_clusters, iterations):
    old_centroids = []
    min_centroids = []
    dist_sum = 0
    min_dist = 0
    for i in range(iterations):
        centroids = get_centroids(matrix, k_clusters)
        dist_sum = getMinDistanceCentroids(matrix, centroids)
        #print(centroids)
        if i == 0:
            min_dist = dist_sum
        if dist_sum < min_dist:
            min_centroids = centroids
            min_dist = dist_sum
        print(min_dist, dist_sum)

    min_clust = getMinClusters(matrix, min_centroids)
    return min_dist, min_clust
        

In [197]:
def getMinClusters(matrix,centroid):
    clust = []
    for point in matrix:
        dists = []
        for centroid in centroids:
            dists.append(eucDist(point, centroid))
        print(dists)
        clust.append(dists.index(min(dists)))
    return clust

In [199]:
centroids

array([[2.09e+05, 2.00e+00, 5.00e+01, 1.00e+00, 5.00e+00],
       [7.40e+05, 6.00e+00, 2.34e+02, 3.00e+00, 4.00e+00],
       [2.89e+05, 3.00e+00, 9.40e+01, 1.00e+00, 4.00e+00],
       [1.58e+05, 3.00e+00, 5.50e+01, 1.00e+00, 1.00e+00]])

In [198]:
getMinClusters(matrix1,centroids)

[434000.0115852533, 965000.0418450768, 514000.020223735, 383000.01443603105]
[584000.0248227734, 1115000.056260985, 664000.0345519569, 533000.0287814251]
[277000.00892599265, 808000.0399826723, 357000.01826470543, 226000.0125110616]
[659000.0304415774, 1190000.0620382337, 739000.0403640043, 608000.0346332227]
[524000.01936832024, 1055000.050456397, 604000.0287433768, 473000.02292811783]
[478000.03461819957, 1009000.0662071336, 558000.0456442634, 427000.04077634466]
[1808000.0283548809, 2339000.054347851, 1888000.0351250658, 1757000.0300902815]
[788000.0280501264, 1319000.0589150859, 868000.0372263817, 737000.0314158745]
[594000.0190151512, 1125000.0496484432, 674000.0279851626, 543000.0221786367]
[1149000.027358137, 1680000.0561880942, 1229000.0353087871, 1098000.0297317847]
[548000.0179835764, 1079000.0487196466, 628000.027038216, 497000.02121730335]
[424000.01621933933, 955000.0474989517, 504000.02577976126, 373000.0200107233]
[879000.0437275302, 1410000.0754432604, 959000.0537992686

[558000.0151991486, 1089000.0453196731, 638000.0237737064, 507000.0180081358]
[359000.01400557073, 890000.0453713471, 439000.0236788149, 308000.01795129816]
[1019000.0346226686, 1550000.0651632245, 1099000.0435864413, 968000.0377794415]
[368000.0136630432, 899000.044917129, 448000.0232031244, 317000.0174416399]
[674000.0376364975, 1205000.0694916993, 754000.0480610065, 623000.0425312987]
[514000.0219503886, 1045000.0534344484, 594000.0317348476, 463000.0259924399]
[679000.037359351, 1210000.0692045435, 759000.047744399, 628000.0421926738]
[1909000.0110400734, 2440000.031047131, 1989000.0156166414, 1858000.0118899355]
[508000.0455895649, 1039000.0766948961, 588000.0571249973, 457000.0530382901]
[397000.01988538995, 928000.0515528003, 477000.0300953869, 346000.02455635753]
[494000.02871862263, 1025000.0605370714, 574000.0392717756, 443000.0338803599]
[389000.00933547545, 920000.0393706514, 469000.01777931734, 338000.0120133134]
[428000.01551518665, 959000.046666318, 508000.024936023, 377

[398000.0147587937, 929000.0459596328, 478000.0242489534, 347000.01846397645]
[1589000.0283650092, 2120000.055303065, 1669000.0354949068, 1538000.0302789335]
[899000.0205622911, 1430000.0494958034, 979000.0285010211, 848000.0229310138]
[1689000.0179511544, 2220000.04169054, 1769000.0238058222, 1638000.0192609888]
[999000.0200745744, 1530000.0482450973, 1079000.0276380905, 948000.0222041137]
[1859000.016907477, 2390000.039493933, 1939000.0223780298, 1808000.0180542034]
[1809000.0378700935, 2340000.0656215805, 1889000.0453975643, 1758000.0400210463]
[313000.01911341795, 844000.0509348325, 393000.02988167823, 262000.0248874034]
[579000.0124913643, 1110000.041683783, 659000.0204559936, 528000.0148380679]
[646000.0195681112, 1177000.049837297, 726000.0283057846, 595000.0225025206]
[799000.0160688359, 1330000.0445372174, 879000.0237155856, 748000.0182312832]
[539000.0209380793, 1070000.0521884332, 619000.0304573902, 488000.0246631654]
[744000.0243118276, 1275000.0549086262, 824000.0332730575

[369000.01127235754, 900000.0420588879, 449000.02033518883, 318000.01452358457]
[508000.0269281489, 1039000.058704522, 588000.0372508492, 457000.03170787636]
[1089000.0175293847, 1620000.044405555, 1169000.0244974333, 1038000.0193232176]
[2259000.02516888, 2790000.0486863796, 2339000.0310617783, 2208000.0265120016]
[307000.01369543944, 838000.0449952255, 387000.02356718277, 256000.01801367124]
[549000.0131841984, 1080000.042848263, 629000.021439785, 498000.0157392066]
[829000.0218389623, 1360000.0514963225, 909000.0301820677, 778000.0244980716]
[529000.0251209824, 1060000.0566495268, 609000.0350985212, 478000.02941004094]
[1099000.0357129204, 1630000.0660950907, 1179000.0445610678, 1048000.0387895985]
[494000.0148967609, 1025000.0452531697, 574000.0236864106, 443000.0178713315]
[634000.006442429, 1165000.032271244, 714000.0126197478, 583000.0077727272]
[748000.0354338227, 1279000.067079748, 828000.045405192, 697000.039683643]
[444000.025488738, 975000.0573112804, 524000.0360381667, 393

[388000.0129445874, 919000.0439347106, 468000.02220192255, 337000.01640207676]
[859000.0128038416, 1390000.0397014383, 939000.0196767836, 808000.0145204207]
[321000.0182651864, 852000.0501022579, 401000.0288818568, 270000.02371157304]
[449000.016179287, 980000.0472418356, 529000.0255359162, 398000.0197248739]
[604000.0239908936, 1135000.0552713643, 684000.0335372799, 553000.0277459306]
[398000.0187663312, 929000.0504569416, 478000.0288828443, 347000.02329971106]
[368000.0251942926, 899000.0567931016, 448000.03609040036, 317000.03124447796]
[468000.0241549139, 999000.0559209194, 548000.0344370427, 417000.0288956825]
[414000.025478562, 945000.0573376967, 494000.0362259602, 363000.03105543944]
[428000.0189392519, 959000.0505020842, 508000.0288602354, 377000.0231803706]
[338000.0213846147, 869000.0532341755, 418000.03223684087, 287000.0272787443]
[699000.0286587977, 1230000.0599951204, 779000.0382573804, 648000.0324683634]
[604000.0242731783, 1135000.0555836991, 684000.0338508764, 553000.0

[669000.0168497756, 1200000.0465216658, 749000.0251542052, 618000.0194619738]
[1650000.0229557573, 2181000.0483464003, 1730000.0294479767, 1599000.0245453406]
[419000.0163890212, 950000.047735262, 499000.02601803537, 368000.0202635864]
[454000.01726762083, 985000.0485248719, 534000.0267949431, 403000.02101860987]
[398000.02233919536, 929000.054163077, 478000.0328640156, 347000.02752161276]
[939000.0333871134, 1470000.0641619035, 1019000.0425088312, 888000.0366953821]
[474000.0232088602, 1005000.0549149239, 554000.0333555946, 423000.0277423159]
[418000.0120442582, 949000.0425563742, 498000.0208845377, 367000.0150722068]
[589000.0263752117, 1120000.0579290164, 669000.0362436463, 538000.0305092928]
[439000.0173462411, 970000.0486561843, 519000.0269576101, 388000.0211829891]
[478000.03178347176, 1009000.0635966284, 558000.0426801059, 427000.0376053848]
[704000.0182713065, 1235000.047985829, 784000.026618622, 653000.0209096475]
[358000.0172709493, 889000.0489994362, 438000.02747716807, 3070

[457000.0158041573, 988000.0468178126, 537000.0250847294, 406000.0192795562]
[507000.0167248518, 1038000.047552022, 587000.0258407149, 456000.0200339908]
[368000.01839538, 899000.0501345926, 448000.0286618294, 317000.0231782326]
[248000.01465725762, 779000.0465064171, 328000.02543597465, 197000.0206345167]
[544000.0156231616, 1075000.0459306967, 624000.0243349355, 493000.0185456386]
[527000.0214136618, 1058000.0527821349, 607000.0310593073, 476000.02528781444]
[484000.0164607435, 1015000.0472004915, 564000.0255726945, 433000.01974364853]
[519000.03546724346, 1050000.0671457122, 599000.0463597645, 468000.0412852546]
[306000.0149313722, 837000.0465872149, 386000.0251580303, 255000.0197176463]
[478000.0252458152, 1009000.0570277487, 558000.0355779559, 427000.03005269216]
[508000.01308686007, 1039000.0430838538, 588000.021557185, 457000.0158055249]
[999000.0202837836, 1530000.0485013064, 1079000.02787164, 948000.0224256327]
[419000.0173269686, 950000.0487247356, 499000.0270601195, 368000.0

[454000.0159240085, 985000.046973603, 534000.0252406361, 403000.01944292756]
[494000.0185404855, 1025000.0497107306, 574000.0279878041, 443000.022185101]
[418000.01381578925, 949000.0446917798, 498000.02298594324, 367000.0171634873]
[484000.0265433877, 1015000.0583729048, 564000.0369769492, 433000.0315150104]
[354000.01418785285, 885000.0456225977, 434000.0239412436, 303000.0182425737]
[284000.0133926053, 815000.0451055202, 364000.023622252, 233000.0182081538]
[599000.0206335556, 1130000.051514158, 679000.0298048594, 548000.023999087]
[414000.0205229464, 945000.052244443, 494000.0307338047, 363000.0251804399]
[408000.0224142151, 939000.0542507971, 488000.0328954907, 357000.02751260396]
[508000.0207736216, 1039000.0521612114, 588000.0304455775, 457000.0246849009]
[424000.02222523524, 955000.0540177996, 504000.03257638786, 373000.02709517325]
[804000.0288190293, 1335000.0596951297, 884000.038006221, 753000.0321918983]
[394000.0249720804, 925000.056815674, 474000.0357932476, 343000.030720

[334000.01661115227, 865000.0483515882, 414000.02689764404, 283000.02145980485]
[408000.0315036753, 939000.0631086241, 488000.04275102273, 357000.038245096]
[679000.0295242998, 1210000.061002891, 759000.039284584, 628000.0335206997]
[348000.0207701143, 879000.0526285536, 428000.0314836437, 297000.0263602682]
[688000.0330305224, 1219000.0647083658, 768000.0430546863, 637000.0373516473]
[658000.0352089657, 1189000.0670151368, 738000.0455182913, 607000.039921745]
[789000.0336235734, 1320000.0650087106, 869000.0432853844, 738000.0374891589]
[748000.0241851601, 1279000.054740421, 828000.0331153375, 697000.0273220942]
[568000.0223257038, 1099000.0535937203, 648000.0318611104, 517000.0260715661]
[368000.0142296193, 899000.0455572847, 448000.02386272256, 317000.018118296]
[454000.02206057217, 985000.0537167498, 534000.0321769653, 403000.0265570711]
[429000.01202564087, 960000.0421921866, 509000.02066011744, 378000.01485978806]
[1409000.043521646, 1940000.0735528336, 1489000.0521766278, 1358000

[499000.02263827604, 1030000.0542242704, 579000.0325777193, 448000.02687611524]
[558000.0152016127, 1089000.0453250678, 638000.0237782127, 507000.01801676495]
[854000.0351955496, 1385000.0665050526, 934000.0447644528, 803000.0389726018]
[547000.0121599633, 1078000.0415278284, 627000.0202208929, 496000.014565524]
[778000.0213663236, 1309000.0512417867, 858000.0298356639, 727000.0241114164]
[398000.0152688439, 929000.0465818072, 478000.02486610814, 347000.01911527326]
[454000.03193171695, 985000.0636939065, 534000.042968163, 403000.03807940264]
[694000.0252816998, 1225000.0562595904, 774000.0345497408, 643000.028734836]
[554000.0203799636, 1085000.051477418, 634000.0297468448, 503000.0239433394]
[288000.0255364572, 819000.0566251506, 368000.03693070466, 237000.03338185418]
[519000.0249797682, 1050000.0565276176, 599000.0349958254, 468000.02932371706]
[789000.0124828896, 1320000.039822348, 869000.0195339469, 738000.0142859077]
[1509000.0175947647, 2040000.0420774505, 1589000.0236856511, 1

[654000.0184472475, 1185000.0485594927, 734000.0270456398, 603000.0212844108]
[358000.0363156406, 889000.0670275565, 438000.0480684905, 307000.04498045275]
[464000.02435129246, 995000.0561361794, 544000.0346783077, 413000.0291598053]
[378000.023474867, 909000.0551254109, 458000.0341451952, 327000.0290259926]
[588000.0343214276, 1119000.0660772992, 668000.0448218548, 537000.0393705758]
[406000.0163903938, 937000.047774812, 486000.02608950547, 355000.0203450698]
[479000.0129665969, 1010000.0431529693, 559000.0215724504, 428000.01578271]
[459000.02177668794, 990000.0534272713, 539000.0318450825, 408000.02620220504]
[584000.018824486, 1115000.0494914788, 664000.0278200295, 533000.0220103185]
[469000.0167324091, 1000000.0478109989, 549000.0260792343, 418000.0202858847]
[1629000.0135687538, 2160000.0359763885, 1709000.0189072555, 1578000.0146726868]
[971000.0133486096, 1502000.039513315, 1051000.019941484, 920000.0149124999]
[528000.0186647724, 1059000.0496397533, 608000.0279276309, 477000.0

[3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,


In [183]:
getClusters(matrix1, 4, 1000)

5179132212.195344 5179132212.195344
5179132212.195344 6214797271.587734
5179132212.195344 5309847162.318358
5179132212.195344 7109692236.232389
5179132212.195344 6606942238.747331
5179132212.195344 5259572216.992307
5179132212.195344 6063972199.983764
5179132212.195344 6365622180.449002
5179132212.195344 5500892131.5837555
5179132212.195344 6365622234.005926
5179132212.195344 5299792163.058563
5179132212.195344 5249517169.575182
5179132212.195344 5299792209.430684
5179132212.195344 6717547341.329059
5179132212.195344 6265072240.970475
5179132212.195344 5812597181.322388
4947867098.359565 4947867098.359565
4947867098.359565 5651717122.608775
4947867098.359565 6104192261.017879
4947867098.359565 4957922081.098106
4947867098.359565 6315347104.188786
4937812153.607979 4937812153.607979
4937812153.607979 5661772138.662534
4937812153.607979 5088637160.348955
4937812153.607979 5490837188.5508
4937812153.607979 5872927071.685486
4937812153.607979 5159022069.676766
4937812153.607979 6667272089.

4696492116.394821 5802542080.5317745
4696492116.394821 5802542175.172533
4696492116.394821 5762322056.746864
4696492116.394821 6265072186.981301
4696492116.394821 6013697432.597528
4696492116.394821 8577722139.091307
4696492116.394821 5601442207.803118
4696492116.394821 5460672151.708815
4696492116.394821 5802542164.481458
4696492116.394821 5893037155.128428
4696492116.394821 6104192129.773908
4696492116.394821 6667272103.111272
4696492116.394821 6003642222.773533
4696492116.394821 5199242092.951797
4696492116.394821 6767822174.27573
4696492116.394821 6104192336.635463
4696492116.394821 4797042165.762118
4696492116.394821 6667272179.919691
4696492116.394821 6335457074.800014
4696492116.394821 5802542193.154138
4696492116.394821 5400342088.3624525
4696492116.394821 6265072121.68877
4696492116.394821 5701992119.71555
4696492116.394821 5913147174.715888
4696492116.394821 6104192114.460139
4696492116.394821 6003642158.40391
4696492116.394821 6818097110.96487
4696492116.394821 6013697268.38

4109280334.8755503 5561222144.998221
4109280334.8755503 6405842161.501669
4109280334.8755503 6094137146.51097
4109280334.8755503 4907647118.654484
4109280334.8755503 6104192293.042108
4109280334.8755503 6033807133.726879
4109280334.8755503 5098692140.970831
4109280334.8755503 5500892196.86933
4109280334.8755503 5802542164.481458
4109280334.8755503 5360122169.807358
4109280334.8755503 6104192179.731775
4109280334.8755503 5400342193.34653
4109280334.8755503 5701992189.073691
4109280334.8755503 6345512117.669006
4109280334.8755503 5701992153.228803
4109280334.8755503 5098692095.5084915
4109280334.8755503 6606942180.85237
4109280334.8755503 5159022118.988265
4109280334.8755503 6365622180.756938
4109280334.8755503 6415897267.835471
4109280334.8755503 5913147354.950038
4109280334.8755503 6104192148.064506
4109280334.8755503 5903092140.89857
4109280334.8755503 6114247113.833562
4109280334.8755503 5460672188.582917
4109280334.8755503 5872927071.685486
4109280334.8755503 6868372123.94348
410928

4109280334.8755503 7622497258.318979
4109280334.8755503 4696492116.163275
4109280334.8755503 7411342159.385757
4109280334.8755503 5299792110.216026
4109280334.8755503 6094137254.008639
4109280334.8755503 6214797068.795916
4109280334.8755503 5963422188.980665
4109280334.8755503 5500892128.241409
4109280334.8755503 5159022136.755152
4109280334.8755503 6566722169.48257
4109280334.8755503 5460672188.40385
4109280334.8755503 5712047128.795086
4109280334.8755503 4907647182.587586
4109280334.8755503 5601442256.224911
4109280334.8755503 5199242133.853804
4109280334.8755503 7099637142.31148
4109280334.8755503 5671827080.820586
4109280334.8755503 6104192146.1511755
4109280334.8755503 6033807184.387683
4109280334.8755503 8929647166.62152
4109280334.8755503 5561222127.753696
4109280334.8755503 5400342195.693304
4109280334.8755503 6717547109.663596
4109280334.8755503 6647162197.634005
4109280334.8755503 5460672134.123207
4109280334.8755503 5460672207.852926
4109280334.8755503 5259572150.209484
4109

4109280334.8755503 5601442255.79162
4109280334.8755503 5802542130.225655
4109280334.8755503 6908592229.680058
4109280334.8755503 6667272117.745101
4109280334.8755503 6365622087.72276
4109280334.8755503 5611497108.658285
4109280334.8755503 5551167145.650249
4109280334.8755503 6315347107.160728
4109280334.8755503 5400342193.473355
4109280334.8755503 5812597237.654739
4109280334.8755503 6003642092.350397
4109280334.8755503 5601442142.326431
4109280334.8755503 6104192204.366696
4109280334.8755503 5500892098.631359
4109280334.8755503 5802542189.292955
4109280334.8755503 6808042306.20923
4109280334.8755503 4756822149.416355
4109280334.8755503 4746767105.205712
4109280334.8755503 5008197167.526221
4109280334.8755503 4947867226.279735
4109280334.8755503 5862872265.193257
4109280334.8755503 5762322132.598496
4109280334.8755503 5903092230.490684
4109280334.8755503 4797042108.926576
4109280334.8755503 4756822190.0905
4109280334.8755503 6013697151.042017
4109280334.8755503 5400342195.693304
410928

(4109280334.8755503,
 [3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,

In [127]:
5762322056.746864
cents = np.random.randint(len(matrix1), size=4)
            centroids = matrix1[cents,:]

In [185]:
getMinDistanceCentroids(matrix1, centroids)

5691937120.310394

In [204]:
centroids[0]

array([2.09e+05, 2.00e+00, 5.00e+01, 1.00e+00, 5.00e+00])

In [187]:
centroids

array([[2.09e+05, 2.00e+00, 5.00e+01, 1.00e+00, 5.00e+00],
       [7.40e+05, 6.00e+00, 2.34e+02, 3.00e+00, 4.00e+00],
       [2.89e+05, 3.00e+00, 9.40e+01, 1.00e+00, 4.00e+00],
       [1.58e+05, 3.00e+00, 5.50e+01, 1.00e+00, 1.00e+00]])

In [203]:
for i in range(100):
    get_centroids(matrix1, 4)

[[2.50e+05 3.00e+00 7.70e+01 2.00e+00 0.00e+00]
 [5.75e+05 4.00e+00 1.25e+02 2.00e+00 0.00e+00]
 [7.60e+05 6.00e+00 2.30e+02 3.00e+00 1.00e+00]
 [6.70e+04 1.00e+00 3.30e+01 1.00e+00 0.00e+00]]
[[3.95e+05 3.00e+00 1.20e+02 2.00e+00 2.00e+00]
 [1.05e+06 5.00e+00 1.83e+02 2.00e+00 2.00e+00]
 [5.49e+05 4.00e+00 1.50e+02 2.00e+00 6.00e+00]
 [2.80e+05 5.00e+00 1.30e+02 2.00e+00 7.00e+00]]
[[1.69e+06 6.00e+00 2.60e+02 3.00e+00 1.20e+01]
 [4.09e+05 4.00e+00 1.52e+02 2.00e+00 1.00e+00]
 [7.49e+05 4.00e+00 1.30e+02 2.00e+00 2.00e+00]
 [2.49e+05 3.00e+00 9.00e+01 2.00e+00 1.00e+00]]
[[2.35e+05 2.00e+00 7.00e+01 1.00e+00 8.00e+00]
 [1.69e+05 2.00e+00 7.30e+01 1.00e+00 5.00e+00]
 [2.49e+05 3.00e+00 7.00e+01 1.00e+00 1.00e+00]
 [1.45e+05 2.00e+00 5.00e+01 1.00e+00 2.00e+00]]
[[6.60e+05 5.00e+00 2.18e+02 2.00e+00 1.00e+00]
 [1.85e+05 3.00e+00 7.50e+01 1.00e+00 4.00e+00]
 [3.60e+05 4.00e+00 1.20e+02 2.00e+00 1.20e+01]
 [5.15e+05 4.00e+00 1.40e+02 2.00e+00 3.00e+00]]
[[2.39e+05 2.00e+00 7.20e+01 1.00e+